# Generated by Django 3.1.1 on 2020-09-09 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensorreading',
            options={'ordering': ['-reading_datetime'], 'verbose_name': 'Sensor Reading', 'verbose_name_plural': 'Sensor Readings'},
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='power_plant',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='plant_readings', to='core.powerplant', verbose_name='Power Plant'),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='sensor_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='core.sensortype', verbose_name='Sensor Type'),
        ),
    ]
